apiVersion: v1
kind: ServiceAccount
metadata:
  # NB(thxCode): name cannot be customized as below:
  # name: {{ template "cloudweav.fullname" . }}
  # because we can easily confirm this resource from the corresponding namespace.
  name: cloudweav
  labels:
{{ include "cloudweav.labels" . | indent 4 }}
    app.kubernetes.io/name: cloudweav
    app.kubernetes.io/component: apiserver
