apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "cloudweav-network-controller.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudweav-network-controller.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "cloudweav-network-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "cloudweav-network-controller.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "cloudweav-network-controller.name" . }}
      hostNetwork: true
      containers:
      - name: cloudweav-network
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - cloudweav-network-controller
        args:
        - agent
        env:
        - name: NODENAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /dev
          name: dev
        - mountPath: /lib/modules
          name: modules
        resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - hostPath:
            path: /dev
          name: dev
        - hostPath:
            path: /lib/modules
          name: modules
