apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cloudweav-networkfs-manager.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "cloudweav-networkfs-manager.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cloudweav-networkfs-manager.name" . }}
rules:
  - apiGroups: [ "" ]
    resources: [ "services", "endpoints", "persistentvolumes" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "cloudweavhci.io" ]
    resources: [ "networkfilesystems", "networkfilesystems/status" ]
    verbs: [ "*" ]
  - apiGroups: [ "coordination.k8s.io" ]
    resources: [ "leases" ]
    verbs: [ "*" ]
  - apiGroups: [ "longhorn.io" ]
    resources: [ "sharemanagers", "sharemanagers/status" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "longhorn.io" ]
    resources: [ "volumeattachments", "volumeattachments/status" ]
    verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cloudweav-networkfs-manager.name" . }}
  labels:
  {{- include "cloudweav-networkfs-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cloudweav-networkfs-manager.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cloudweav-networkfs-manager.name" . }}
    namespace: {{ .Release.Namespace }}
