apiVersion: v2
name: cloudweav
version: 0.0.0-dev
appVersion: 0.1.x
description: Cloudweav is an open source Hyper-Converged Infrastructure(HCI) solution based on Kubernetes.
icon: https://cloudweav.github.io/images/logo_horizontal.svg
type: application
keywords:
  - virtualization
  - HCI
home: https://github.com/cloudweav/cloudweav
sources:
  - https://github.com/cloudweav/cloudweav
dependencies:
  - name: kubevirt-operator
    version: 0.2.1
    repository: file://dependency_charts/kubevirt-operator
    condition: kubevirt-operator.enabled
    tags:
      - kubevirt
      - operator
  - name: kubevirt
    version: 0.1.0
    repository: file://dependency_charts/kubevirt
    condition: kubevirt.enabled
    tags:
      - kubevirt
      - crd
  - name: cloudweav-network-controller
    version: 0.5.1
    repository: https://charts.cloudweavhci.io
    condition: cloudweav-network-controller.enabled
  - name: cloudweav-networkfs-manager
    version: 0.1.0
    repository: https://charts.cloudweavhci.io
    condition: cloudweav-networkfs-manager.enabled
  - name: cloudweav-node-disk-manager
    version: 0.7.7
    repository: https://charts.cloudweavhci.io
    condition: cloudweav-node-disk-manager.enabled
  - name: csi-snapshotter
    version: 0.2.0
    repository: file://dependency_charts/csi-snapshotter
    condition: csi-snapshotter.enabled
  - name: longhorn
    version: 1.7.2
    repository: https://charts.longhorn.io
    condition: longhorn.enabled
  - name: kube-vip
    version: 0.6.1
    repository: https://kube-vip.github.io/helm-charts
  - name: cloudweav-load-balancer
    version: 0.4.0
    repository: https://charts.cloudweavhci.io
  - name: whereabouts
    version: 0.1.1
    repository: file://dependency_charts/whereabouts
    condition: whereabouts.enabled
  - name: cloudweav-node-manager
    version: 0.3.1
    repository: https://charts.cloudweavhci.io
  - name: snapshot-validation-webhook
    version: 0.2.0
    repository: file://dependency_charts/snapshot-validation-webhook
