#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

echo "Start building ISO image"

CLOUDWEAV_INSTALLER_VERSION=master

git clone --branch ${CLOUDWEAV_INSTALLER_VERSION} --single-branch --depth 1 https://github.com/cloudweav/cloudweav-installer.git ../cloudweav-installer

cd ../cloudweav-installer/scripts

./ci

cd ..
CLOUDWEAV_DIR=../cloudweav

mkdir -p ${CLOUDWEAV_DIR}/dist/artifacts
cp dist/artifacts/* ${CLOUDWEAV_DIR}/dist/artifacts
cp -r dist/cloudweav-cluster-repo  ${CLOUDWEAV_DIR}/dist

