apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cloudweav-node-disk-manager.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "cloudweav-node-disk-manager.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cloudweav-node-disk-manager.name" . }}
rules:
  - apiGroups: [ "cloudweavhci.io" ]
    resources: [ "blockdevices", "lvmvolumegroups", "lvmvolumegroups/status" ]
    verbs: [ "*" ]
  - apiGroups: [ "longhorn.io" ]
    resources: [ "nodes" ]
    verbs: [ "get", "list", "watch", "update", "patch" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps", "events" ]
    verbs: [ "get", "watch", "list", "update", "create" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cloudweav-node-disk-manager.name" . }}
  labels:
  {{- include "cloudweav-node-disk-manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cloudweav-node-disk-manager.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "cloudweav-node-disk-manager.name" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudweav-node-disk-manager-webhook
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudweav-node-disk-manager-webhook
rules:
  - apiGroups: [ "" ]
    resources: [ "secrets", "configmaps" ]
    verbs: [ "*" ]
  - apiGroups: [ "" ]
    resources: [ "persistentvolumes" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "storage.k8s.io" ]
    resources: [ "storageclasses" ]
    verbs: [ "*" ]
  - apiGroups: [ "cloudweavhci.io" ]
    resources: [ "blockdevices", "lvmvolumegroups", "lvmvolumegroups/status" ]
    verbs: [ "*" ]
  - apiGroups: [ "apiregistration.k8s.io" ]
    resources: [ "apiservices" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "apiextensions.k8s.io" ]
    resources: [ "customresourcedefinitions" ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ "admissionregistration.k8s.io" ]
    resources: [ "validatingwebhookconfigurations", "mutatingwebhookconfigurations" ]
    verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudweav-node-disk-manager-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cloudweav-node-disk-manager-webhook
subjects:
  - kind: ServiceAccount
    name: cloudweav-node-disk-manager-webhook
    namespace: {{ .Release.Namespace }}
