---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudweav-node-disk-manager-webhook.labels" . | nindent 4 }}
  name: cloudweav-node-disk-manager-webhook
spec:
  replicas: {{ .Values.webhook.replicas }}
  selector:
    matchLabels:
      {{- include "cloudweav-node-disk-manager-webhook.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cloudweav-node-disk-manager-webhook.labels" . | nindent 8 }}
    spec:
      serviceAccountName: cloudweav-node-disk-manager-webhook
      containers:
        - name: cloudweav-node-disk-manager-webhook
          image: "{{ .Values.webhook.image.repository }}:{{ .Values.webhook.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.webhook.image.pullPolicy }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - node-disk-manager-webhook
---
apiVersion: v1
kind: Service
metadata:
  name: cloudweav-node-disk-manager-webhook
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    {{- include "cloudweav-node-disk-manager-webhook.selectorLabels" . | nindent 4 }}
  ports:
    - name: https
      port: 443
      protocol: TCP
      targetPort: {{ .Values.webhook.httpsPort }}